In [17]:
import numpy as np

In [18]:
X = np.random.randint(1,100, size=(4, 4))
print(X)

[[22 15 69 66]
 [69 49 61 27]
 [ 6  3 42 93]
 [ 4 13 39 93]]


In [19]:
X_row = X.reshape(4,4)
print(X_row) # No change, and this is for the following calculation of the sum of each rows.
X_column = X.transpose()
print(X_column)

[[22 15 69 66]
 [69 49 61 27]
 [ 6  3 42 93]
 [ 4 13 39 93]]
[[22 69  6  4]
 [15 49  3 13]
 [69 61 42 39]
 [66 27 93 93]]


In [26]:
# I have no idea about how to use lambda in numpy as apply function can not be used.
print(X_row.sum(axis= 0))
print(X_column.sum(axis = 0))

[101  80 211 279]
[172 206 144 149]
